version: '3.2'
services:
  unbound:
    image: ofthesun9/unbound-mailu:master
    ports:
     - 0.0.0.0:53:53/tcp
     - 0.0.0.0:53:53/udp
    deploy:
      mode: global
#      mode: replicated
#      replicas: 1
      placement:
        constraints: [node.role == worker]

#networks:
#  default:
#    external:
#      name: my-attachable-overlay
