version: '2'
services:
  unbound:
    container_name: unbound
    image: ofthesun9/unbound-mailu:master
    restart: unless-stopped
    ports:
    - 0.0.0.0:53:53/tcp
    - 0.0.0.0:53:53/udp
networks:
  default:
    external:
      name: mailu_default
